### ISSUE TITLE
What's the annotation format the target domain should give?

### ISSUE THREAD

**Issue by luoluo123123123123** [XuYunqiu/H2FA_R-CNN#10]
In your example the target domain Clipart, you give the full annotation just like this .
![image](https://user-images.githubusercontent.com/123624781/214785573-14ec92d0-4057-49b0-b8a5-7c7895e55704.png)

I 'm confused that if I use my own dataset,the annotation of my target data will be the full annotation or not.

**Comment by XuYunqiu** [comment]
Hi, the Clipart, Watercolor and Comic datasets also contain fully supervised annotations. Such instance-level annotations can be used for training oracle models or other purposes.

In H<sup>2</sup>FA R-CNN, we only extract the category information of target domains and convert them into image-level labels.
https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/modeling/roi_heads/roi_heads.py#L51-L69

A simple solution for using the custom dataset without full annotations is to give some random box coordinates information in the annotations files. For instance, you can set the `xmin` and `ymin` to 1, and set the `xmax` and `ymax` to 2. For images with multiple objects of same classes, you only need to write ONE set of information (i.e., `name`, `bnbbox` and etc) for each positive class.
