### ISSUE TITLE
I want to know if if I delete the TRAIN part, it will become an vanilla faster RCNN？

### ISSUE THREAD

**Issue by luoluo123123123123** [XuYunqiu/H2FA_R-CNN#11]
DATASETS:
    #TRAIN: ('clipart1k_traintest',)
    TRAIN_SOURCE: ('voc_2007_trainval', 'voc_2012_trainval')
    TEST: ('clipart1k_traintest',)

**Comment by luoluo123123123123** [comment]
It seems that not work. I want to ask how to compare it with vanilla fasterRCNN more conveniently

**Comment by XuYunqiu** [comment]
Hi, after adding some task specific features, current code does not support vanilla faster R-CNN.
I think you can easily train it with the vanilla Detectron2 code after registering the new datasets.

Currently, there is no plans to integrate vanilla faster R-CNN into this repo. But any pull requests are welcome.
