### ISSUE TITLE
loss_local_da doesn't change

### ISSUE THREAD

**Issue by 1184125805** [XuYunqiu/H2FA_R-CNN#12]
![image](https://user-images.githubusercontent.com/38450078/221784324-8e8c5577-0a91-4441-af22-0b21de221105.png)
when I use custom dataset,the value of loss_local_da doesn't change

**Comment by 1184125805** [comment]
It change to 0.249 after a long time, I don't know if this value doesn't change,what it stands for
![image](https://user-images.githubusercontent.com/38450078/221784966-54a5d953-a1f8-4293-9c36-03992c501c74.png)

**Comment by 1184125805** [comment]
![image](https://user-images.githubusercontent.com/38450078/221833901-f326fea4-0e95-4184-9655-76382496c64b.png)
after training the loss_local_da is still around 0.245

**Comment by XuYunqiu** [comment]
Hi, I'm not sure what's happen in the custom dataset.
But in my view, as an adversarial loss, it is normal for `loss_local_da` to fluctuate during training.
