### ISSUE TITLE
I have some questions about the data

### ISSUE THREAD

**Issue by zml110120** [XuYunqiu/H2FA_R-CNN#13]
Dear author,
If I only use the custom data set as target domain data and VOC as source domain data. But the custom dataset has categories that are not present in VOC. Will this category not present in VOC be trained?

如果我才用自定义数据集作为目标数据，使用VOC作为源域数据。但是自定义数据集中有VOC中没有出现的类别，这种没有在VOC中出现的类别也会得到训练吗？

**Comment by XuYunqiu** [comment]
Hi, the categories not present in VOC can be trained in our framework. 
However, I'm not sure whether these categories can obtain any benefits from the source domain. If not, these categories will be trained in a pure image-level WSOD way.
Concretely, these categories only receive the supervision from the target domain, and might not get any guidance from the source domain.
