### ISSUE TITLE
How to draw this picture in your paper?

### ISSUE THREAD

**Issue by luoluo123123123123** [XuYunqiu/H2FA_R-CNN#14]
![image](https://user-images.githubusercontent.com/123624781/224032360-05556071-7d36-483b-a7ce-dbb3795a4c34.png)

**Comment by XuYunqiu** [comment]
Hi, I'm sorry I didn't keep the code for visualization anymore. You can use seaborn or matplotlib to plot these figures. 
Here are some hints for plotting these figures:
1. extract instance-level feature embeddings using all the ground-truth boxes and ROI Align (set the output_size to 1);
2. compute the center of the source-domain ground-truths, and the Euclidean distances of each ground-truths to the center;
3. plot the distance distribution of the source domain;
4. compute the center of the target domain, the distances of each ground-truths to the center, and the distance between source and target centers;
5. add the distance of two centers and plot the distance distribution of the target domain.
