### ISSUE TITLE
Where is the code of I-Classifier and image-level recognition path?

### ISSUE THREAD

**Issue by flowerstree** [XuYunqiu/H2FA_R-CNN#15]
Excuse me, could you please tell me where the code of Specific methods is? I want to study your specific algorithm, but I haven't found the location. Would you please tell me the specific location of the code for these methods

**Comment by XuYunqiu** [comment]
Hi, 

The code for the `I-classifier` is in 
https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/modeling/meta_arch/rcnn.py#L466-L500

The code for the `image-level recognition path` is in 
https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/modeling/roi_heads/roi_heads.py#L477-L531

I'm closing this issue, but feel free to reopen it if you have further questions.

**Comment by flowerstree** [comment]
> Hi,
> 
> The code for the `I-classifier` is in
> 
> https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/modeling/meta_arch/rcnn.py#L466-L500
> 
> The code for the `image-level recognition path` is in
> 
> https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/modeling/roi_heads/roi_heads.py#L477-L531
> 
> I'm closing this issue, but feel free to reopen it if you have further questions.

thank you so much !!
