### ISSUE TITLE
How to get the AP of each category ? I just can see the AP/AP50/AP75 on tensorboard without more details? 

### ISSUE THREAD

**Issue by judyxt** [XuYunqiu/H2FA_R-CNN#16]
## ❓ How to do something using detectron2

Describe what you want to do, including:
1. what inputs you will provide, if any:
2. what outputs you are expecting:

## ❓ What does an API do and how to use it?
Please link to which API or documentation you're asking about from
https://detectron2.readthedocs.io/

NOTE:

1. Only general answers are provided.
   If you want to ask about "why X did not work", please use the
   [Unexpected behaviors](https://github.com/facebookresearch/detectron2/issues/new/choose) issue template.

2. About how to implement new models / new dataloader / new training logic, etc., check documentation first.

3. We do not answer general machine learning / computer vision questions that are not specific to detectron2, such as how a model works, how to improve your training/make it converge, or what algorithm/methods can be used to achieve X.

**Comment by XuYunqiu** [comment]
Hi, the per-class AP50 results `results_tex` are reported after evaluation and not stored in tensorboard. 
If you want to save these results in tensorboard, you can modify the corresponding code.
https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/evaluation/cdod_evaluation.py#L129-L133
I'm closing this issue, but feel free to reopen it if you have further questions.
