### ISSUE TITLE
error: command '/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1

### ISSUE THREAD

**Issue by luoqianxi** [XuYunqiu/H2FA_R-CNN#17]
(detectron2_H2FA) lqx@tiggers-X299-UD4-Pro:~/H2FA_R-CNN-main$ python setup.py install
running install
running bdist_egg
running egg_info
writing detectron2.egg-info/PKG-INFO
writing dependency_links to detectron2.egg-info/dependency_links.txt
writing requirements to detectron2.egg-info/requires.txt
writing top-level names to detectron2.egg-info/top_level.txt
reading manifest file 'detectron2.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'detectron2.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
running build_ext
building 'detectron2._C' extension
/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/bin/x86_64-conda_cos6-linux-gnu-cc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem /home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/include -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -isystem /home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/include -fPIC -DWITH_CUDA -I/home/tiggers/Newdisk/lqx/H2FA_R-CNN-main/detectron2/layers/csrc -I/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/lib/python3.6/site-packages/torch/include -I/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/lib/python3.6/site-packages/torch/include/torch/csrc/api/include -I/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/lib/python3.6/site-packages/torch/include/TH -I/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/lib/python3.6/site-packages/torch/include/THC -I/home/tiggers/Newdisk/lqx/cuda-10.2/include -I/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/include/python3.6m -c /home/tiggers/Newdisk/lqx/H2FA_R-CNN-main/detectron2/layers/csrc/vision.cpp -o build/temp.linux-x86_64-3.6/home/tiggers/Newdisk/lqx/H2FA_R-CNN-main/detectron2/layers/csrc/vision.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=_C -D_GLIBCXX_USE_CXX11_ABI=1 -std=c++11
x86_64-conda_cos6-linux-gnu-cc: error: /home/tiggers/Newdisk/lqx/H2FA_R-CNN-main/detectron2/layers/csrc/vision.cpp: No such file or directory
x86_64-conda_cos6-linux-gnu-cc: fatal error: no input files
compilation terminated.
error: command '/home/tiggers/Newdisk/lqx/anaconda3/envs/detectron2_H2FA/bin/x86_64-conda_cos6-linux-gnu-cc' failed with exit status 1

my torch=1.4 cuda=9.2,gcc=7.3 please help me

**Comment by XuYunqiu** [comment]
Hi, please check the Detectron2 version. I use Detectron2 v0.2 in my experiments.
You should also double check the cuda version, as I see `cuda-10.2` in the log you posted.

**Comment by luoqianxi** [comment]
hello,can you tell me that Requirements for the graphics card？

**Comment by XuYunqiu** [comment]
The results and pre-trained models were obtained using two NVIDIA V100-32G GPUs for benchmarking.
I don't think the GPU type will be a problem. I also debugged and ran the code using different GPUs.

**Comment by XuYunqiu** [comment]
I'm closing this issue, but let me know if you have further questions.
