### ISSUE TITLE
Question about Oracle？

### ISSUE THREAD

**Issue by judyxt** [XuYunqiu/H2FA_R-CNN#18]
Hello！How can i get the mAP of Oracle mode? I used to set configs like these:
  TEST:
  - comic2k_test
  TRAIN:
  - comic2k_train
  TRAIN_SOURCE:
  - comic2k_train
  but i got wrong results.  What should i do to train oracle model? Thanks for replying!

**Comment by XuYunqiu** [comment]
The oracle model in our paper indicates the detector trained with BOTH fully supervised `target` and `source` datasets.

This repo doesn't contain the code for oracle models. You can use Detectron2 to train the oracle model of comic2k dataset, after registering some custom datasets (i.e., `comic2k_train`, `cdod_voc_2007_trainval` and `cdod_voc_2012_trainval`).

The config should be like as follows
DATASETS:
-    TRAIN: ('cdod_voc_2007_trainval', 'cdod_voc_2012_trainval', 'comic2k_train')
-    TEST: ('comic2k_test',)

**Comment by judyxt** [comment]
Thanks for you reply! But if I just use detectron2 to train Oracle model, it dosen't contain novel modules in your paper?  Can I just set TRAIN_SOURCE to “cdod_voc_2007_trainval”、“cdod_voc_2012_trainval”、“comic2k_train” in this repo?

**Comment by XuYunqiu** [comment]
The oracle model is the standard Faster R-CNN.
The introduced new modules in our paper are designed for CDWSOD, which might decrease the detection performance in a fully supervised setting.

In addition, this repo seems not to support training detectors with both `TRAIN_SOURCE` and `TRAIN`. So, you have to modify some code for your purpose.
A simpler solution is train a Faster R-CNN using Detectron2 as I mentioned before.

**Comment by judyxt** [comment]
Thank you! I understood!
