### ISSUE TITLE
The structure of image classifier

### ISSUE THREAD

**Issue by tredsx** [XuYunqiu/H2FA_R-CNN#20]
Since the structure of image is different from other's, can you show us the actual structure of  image classifier in picture?

**Comment by XuYunqiu** [comment]
I'm not clear what does the `different structure of image` exactly mean. We use the same images as in prior works.

The image classifier is implemented by a 1X1 Conv layer with an average pooling layer, as shown in 
https://github.com/XuYunqiu/H2FA_R-CNN/blob/499c1d90833c475fd9f288bb6bb90829989def64/detectron2/modeling/meta_arch/rcnn.py#L466-L500

**Comment by XuYunqiu** [comment]
I'm closing this issue, but let me know if you have further questions.
