### ISSUE TITLE
RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by anranbixin** [XuYunqiu/H2FA_R-CNN#3]
自己运行的时候报错：
File "/root/H2FA_R-CNN/detectron2/modeling/proposal_generator/rpn.py", line 303, in label_and_sample_anchors
    matched_idxs, gt_labels_i = retry_if_cuda_oom(self.anchor_matcher)(match_quality_matrix)
  File "/root/H2FA_R-CNN/detectron2/utils/memory.py", line 70, in wrapped
    return func(*args, **kwargs)
  File "/root/H2FA_R-CNN/detectron2/modeling/matcher.py", line 88, in __call__
    assert torch.all(match_quality_matrix >= 0)
RuntimeError: CUDA error: device-side assert triggered
请问是什么原因呢？

**Comment by XuYunqiu** [comment]
This is a PyTorch bug also mentioned in  https://github.com/facebookresearch/detectron2/issues/2837.
You could downgrade you CUDA and PyTorch to avoid this issue. I think you can try `CUDA 9.2` + `PyTorch 1.4`  as I used before.

I'm closing this issue, but feel free to reopen it if you have further questions.

**Comment by anranbixin** [comment]
很感谢您的解答（作者的那个环境是 ubuntu16、torch1.4、cuda9.0的吗），实验结果的模型是否可以提供呢？如果方便的话，希望能够提供一下，可以发送至我的邮箱吗？我的邮箱是1217178719@qq.com（学校邮箱是：202122000541@stu.swpu.edu.cn，希望的是能够发送QQ邮箱）。如果可以的话，很感谢作者的提供。

**Comment by XuYunqiu** [comment]
I used `CUDA 9.2` + `PyTorch 1.4` on servers with `Ubuntu` or `CentOS`. 
I'm not sure if `CUDA 9.0` will run smoothly. I think it could work, if it matches the installation requirements of Detectron2 v0.2. 

The URL links for our pre-trained models are available in this [table](https://github.com/XuYunqiu/H2FA_R-CNN#main-results-with-pre-trained-models). You can download them via Google Drive or Baidu Pan.

**Comment by anranbixin** [comment]
您好，很感谢您的回答。还有一个问题想请教一下您，你们的特征对齐方法是可以移植出去的吗？因为我这边实在是没办法配出合适的（cuda版本没有合适），但是我在移植出去之后，特征对齐的损失出现了nan，因为自己的是分别得到的source_feature_res2和target_feature_res2，做了resize之后进行了cat，然后丢到了LocalDAHead进行的特征对齐，但是损失一直没有降下来，而且还出现了nan，请问是什么原因呢？希望您能够解惑。

**Comment by XuYunqiu** [comment]
I don't think there will be any problem adding them to other Faster R-CNN based frameworks or other platforms.
You may need tune some hyper-parameters (e.g., LR and loss weights) for different implementations.

The `LocalDAHead` is borrowed and re-implemented from SWDA. You can also find a different implementation from their repository: https://github.com/VisionLearningGroup/DA_Detection
