### ISSUE TITLE
How to train my own datasets but not VOC？

### ISSUE THREAD

**Issue by 1184125805** [XuYunqiu/H2FA_R-CNN#4]
Thank you very much for your guidence

**Comment by XuYunqiu** [comment]
A  simple solution is converting annotations of the custom datasets into VOC format and registering them in [`detectron2/data/datasets/cdod.py`](https://github.com/XuYunqiu/H2FA_R-CNN/blob/main/detectron2/data/datasets/cdod.py).

Alternatively, you can implement some functions to load data and annotations by yourself. More information about how to use custom datasets is available at https://detectron2.readthedocs.io/en/latest/tutorials/datasets.html

I believe I've answered your question and as such I'm closing this issue, but let us know if you have further questions
