### ISSUE TITLE
Where is 

### ISSUE THREAD

**Issue by zml110120** [XuYunqiu/H2FA_R-CNN#7]
Hi!
How can i get `cdod_faster_rcnn_R_101_DC5.yaml` file?

![image](https://user-images.githubusercontent.com/29172684/209573442-614dc180-d877-4fca-bc60-cb244df839a7.png)

![image](https://user-images.githubusercontent.com/29172684/209573483-ca87d718-1fd6-4ed1-a0a2-93eedbeb5333.png)

**Comment by XuYunqiu** [comment]
Sorry for the typos.
The config file for VOC -> Clipart<sub>all</sub>  adaptation should be `../configs/CrossDomain-Detection/h2fa_rcnn_R_101_DC5_clipartall.yaml`
If you want to evaluate the trained models for other datasets, you should change the config file correspondingly.
