### ISSUE TITLE
Some error about own dataset

### ISSUE THREAD

**Issue by zml110120** [XuYunqiu/H2FA_R-CNN#8]
## ❓ Some error about own dataset

Hi! I did use my own data set (with 14 categories), but I got the following error. How can i solve it?

![image](https://user-images.githubusercontent.com/29172684/209574600-f6edcc2a-1516-4a97-82aa-3c1ec64ffd75.png)

**Comment by XuYunqiu** [comment]
The source dataset `voc_2012_trainval` has 20 classes, while the target dataset `cp_train` has 14 classes.
You need to register new custom VOC datasets with 14 classes to filter out the 6 dummy classes in the standard VOC datasets.

You can refer to the following code to register the custom VOC datasets.
https://github.com/XuYunqiu/H2FA_R-CNN/blob/6b76bd797049a9a129ae67e129d31b27e89f0445/detectron2/data/datasets/cdod.py#L129-L137

**Comment by zml110120** [comment]
@XuYunqiu Dear author,
Do you mean to register like the first picture? But there are still some errors (just like the second picture). `cp_train cp_val` are my own dataset.
![image](https://user-images.githubusercontent.com/29172684/209643198-d3bc63b1-99d2-47e7-812a-293c4b9030a6.png)

![image](https://user-images.githubusercontent.com/29172684/209643260-87621b48-6e4d-424c-9fc3-5e5dd7583ff6.png)

**Comment by XuYunqiu** [comment]
You should register both source and target datasets, if you used custom datasets.
Besides registering the target datasets `cp_train` and `cp_val` with 14 classes, you need to register a custom source dataset (i.e., a custom VOC with 14 classes).

The above code I posted is an example for registering the custom VOC dataset with 6 classes.

**Comment by XuYunqiu** [comment]
I'm closing this issue, but let me know if you have further questions.
